; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.14"

; Modules
projects[autologout][version] = "2.4"
projects[cck][version] = "2.6"
projects[computed_field][version] = "1.0-beta3"
projects[content_taxonomy][version] = "1.0-rc2"
projects[ctools][version] = "1.3"
projects[devel][version] = "1.18"
projects[feeds][version] = "1.0-beta1"
projects[fivestar][version] = "1.19"
projects[json_server][version] = "2.0-alpha2"
projects[menu_inject_block][version] = "1.0"
projects[mollom][version] = "1.15"
projects[pathauto][version] = "1.3"
;projects[services][version] = "2.2"
projects[tabs][version] = "1.x-dev"
projects[token][version] = "1.12"
projects[user_import][version] = "2.3"
projects[views_datasource][version] = "1.0-beta2"
projects[views][version] = "2.8"
projects[viewsphpfilter][version] = "1.0"
projects[votingapi][version] = "2.0-rc2"
projects[xmlrpctester][version] = "1.x-dev"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[poof][download][type] = "svn"
projects[poof][download][url] = "https://svn.library.cornell.edu/poof/trunk/module"

projects[poof][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[culpoof][download][type] = "svn"
projects[culpoof][download][url] = "https://svn.library.cornell.edu/culpoof/trunk/theme"
projects[culpoof][type] = "theme"

